todo/todo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from todoapp.views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('django.contrib.auth.urls')),
    url(r'^$', home, name='home'),
    url(r'^', include('todoapp.urls', namespace='todoapp'))
]

todo/todoapp/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import AddTodo, DeleteTodo

app_name = 'todo'

urlpatterns = [
    url(r'^add/', AddTodo, name='add'),
    url(r'^delete/(?P<todo_id>\d+)/', DeleteTodo, name='delete'),
]

todo/todoapp/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime


class TodoItem(models.Model):
    title = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'TODOs'
        verbose_name_plural = 'TODOs'

todo/todoapp/views.py
"""
View for my todo
"""
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import TodoItem
# Create your views here.

def home(request):
    """
    List of all todo items
    """
    todo_list = TodoItem.objects.filter(author=request.user.id)
    return render(request, 'todoapp/home.html', {'todo_list':todo_list})

def AddTodo(request):
    item = TodoItem(title=request.POST['title'], author=request.user)
    item.save()
    return HttpResponseRedirect('/')

def DeleteTodo(request, todo_id):
    item = get_object_or_404(TodoItem, pk=todo_id)
    item.delete()
    return HttpResponseRedirect('/')

todo/todoapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Todo Application{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

todo/todoapp/templates/todoapp/home.html
{% extends 'base.html' %}

{% block title %}Todo Application{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <ul>
        {% for todo in todo_list %}
            <li>{{ todo.title }}</li>
            <form action="{% url 'todo:delete' todo_id=todo.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="remove">
            </form>
        {% empty %}
            <li>No todo exist </li>
        {% endfor r%}
</ul>
<form action="{% url 'todo:add' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="submit" value="save">
</form>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}